version: '2.2'
services:
  server:
    image: klakegg/hugo:latest-ext
    container_name: hugo_server
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"
    command: ["server", "--disableFastRender"]
